services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:5000"
    tty: true
